### ISSUE TITLE
[Feature] creer le composant ActualityCard.tsx

### ISSUE THREAD

**Issue by farid1111** [betagouv/delta-v#381]
creer le composant ActualityCard.tsx

<img width="214" alt="ActualityCard" src="https://user-images.githubusercontent.com/18749800/218326576-72207b9d-4aea-4e79-b3e4-a76a84348a56.png">

Ce composant aura les props:
- title:string;
- creationDate: Date;
- content: string;

**Comment by farid1111** [comment]
<img width="214" alt="ActualityCard" src="https://user-images.githubusercontent.com/18749800/218326576-72207b9d-4aea-4e79-b3e4-a76a84348a56.png">

**Comment by Touan95** [comment]
<img width="455" alt="Capture d’écran 2023-02-21 à 11 14 23" src="https://user-images.githubusercontent.com/17031570/220397596-a9c8f415-eb1e-4f9d-9bb1-f8da02035837.png">
